//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Define_MST> Define_MST { get; set; }
        public virtual DbSet<Employee_MST> Employee_MST { get; set; }
        public virtual DbSet<Employee_TRN> Employee_TRN { get; set; }
        public virtual DbSet<Request_LST> Request_LST { get; set; }
    
        public virtual ObjectResult<string> GetNewEmployeeID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetNewEmployeeID");
        }
    
        public virtual ObjectResult<string> GetNewRequestID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetNewRequestID");
        }
    }
}
